---
i18n:
    name: "Cleaning up Liska Linux Installer packages..."

dontChroot: false
timeout: 300
script:
    - command: "lkpm -d calamares --noconfirm"
    - command: "rm -rf /etc/calamares"
    - command: "rm -f /usr/bin/calamares"