---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       remove-installer
  module:   shellprocess
  config:   remove-installer.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - grubcfg
  - umount
  - remove-installer
- show:
  - finished

logging:
  level: 7
  to: syslog