-- LISKA LINUX HYPRLAND CONFIGURATION
autogenerated = 0

monitor = {
    ",preferred,auto,1"
}

env = {
    "LIBVLC_PLUGIN_PATH,/usr/lib/vlc/plugins",
    "XDG_CURRENT_DESKTOP,Hyprland",
    "XDG_SESSION_TYPE,wayland",
    "XDG_SESSION_DESKTOP,Hyprland"
}

exec-once = {
    "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
    "systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
    "systemctl --user start pipewire.service",
    "systemctl --user start wireplumber.service",
    "/usr/bin/waybar",
    "/usr/bin/mako",
    "/usr/bin/hyprpaper"
}

cursor = {
    no_hardware_cursors = true,
    no_break_fs_cursor = false
}

input = {
    kb_layout = "us",
    follow_mouse = 1,
    sensitivity = 0.5,
    touchpad = {
        natural_scroll = true,
        drag_lock = false
    }
}

general = {
    gaps_in = 8,
    gaps_out = 14,
    border_size = 2,
    ["col.active_border"] = "rgba(58a6ffee) rgba(39c5bbee) 45deg",
    ["col.inactive_border"] = "rgba(161b22aa)",
    layout = "dwindle",
    no_cursor_warps = true,
    allow_tearing = true
}

decoration = {
    rounding = 14,
    active_opacity = 0.88,
    inactive_opacity = 0.75,
    fullscreen_opacity = 1.0,
    blur = {
        enabled = true,
        size = 8,
        passes = 3,
        new_optimizations = true,
        ignore_opacity = true,
        xray = false
    },
    drop_shadow = true,
    shadow_range = 20,
    shadow_render_power = 3,
    ["col.shadow"] = "rgba(00000044)"
}

animations = {
    enabled = true,
    bezier = {
        "glassy, 0.05, 0.9, 0.1, 1.05"
    },
    animation = {
        "windows, 1, 5, glassy",
        "windowsOut, 1, 5, glassy, popin 80%",
        "border, 1, 8, default",
        "fade, 1, 5, default",
        "workspaces, 1, 6, glassy, slide"
    }
}

dwindle = {
    preserve_split = true,
    smart_split = true,
    smart_resizing = true
}

local mainMod = "SUPER"

bind = {
    mainMod .. ", Return, exec, /usr/bin/alacritty",
    mainMod .. ", B, exec, /usr/bin/firefox",
    mainMod .. ", Q, killactive,",
    mainMod .. " SHIFT, E, exit,",
    mainMod .. ", Space, exec, /usr/bin/rofi -show drun",
    mainMod .. ", F, fullscreen,",
    mainMod .. ", M, fullscreen, 1",
    mainMod .. ", V, togglefloating,",
    mainMod .. ", P, pseudo,",
    mainMod .. ", J, togglesplit,",
    mainMod .. ", W, exec, $HOME/.config/hypr/scripts/set-wallpaper.sh",
    mainMod .. ", S, exec, pkexec $HOME/.config/hypr/scripts/launch-installer.sh",
    mainMod .. ", 1, workspace, 1",
    mainMod .. ", 2, workspace, 2",
    mainMod .. ", 3, workspace, 3",
    mainMod .. ", 4, workspace, 4",
    mainMod .. ", 5, workspace, 5",
    mainMod .. " SHIFT, 1, movetoworkspace, 1",
    mainMod .. " SHIFT, 2, movetoworkspace, 2",
    mainMod .. " SHIFT, 3, movetoworkspace, 3",
    mainMod .. " SHIFT, 4, movetoworkspace, 4",
    mainMod .. " SHIFT, 5, movetoworkspace, 5",
    mainMod .. ", left, movefocus, l",
    mainMod .. ", right, movefocus, r",
    mainMod .. ", up, movefocus, u",
    mainMod .. ", down, movefocus, d"
}