-- LISKA LINUX HYPRLAND CONFIGURATION
autogenerated = 0

monitor = {
    ",preferred,auto,1"
}

exec_once = {
    "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
    "waybar",
    "mako",
    "hyprpaper",
    "pipewire"
}

input = {
    kb_layout = "us",
    follow_mouse = 1,
    touchpad = {
        natural_scroll = true
    }
}

general = {
    gaps_in = 8,
    gaps_out = 14,
    border_size = 2,
    ["col.active_border"] = "rgba(58a6ffee) rgba(39c5bbee) 45deg",
    ["col.inactive_border"] = "rgba(161b22aa)",
    layout = "dwindle",
    no_cursor_warps = true
}

decoration = {
    rounding = 14,
    active_opacity = 0.88,
    inactive_opacity = 0.75,
    fullscreen_opacity = 1.0,
    blur = {
        enabled = true,
        size = 8,
        passes = 3,
        new_optimizations = true,
        ignore_opacity = true,
        xray = false
    },
    drop_shadow = true,
    shadow_range = 20,
    shadow_render_power = 3,
    ["col.shadow"] = "rgba(00000044)"
}

animations = {
    enabled = true,
    bezier = {
        "glassy, 0.05, 0.9, 0.1, 1.05"
    },
    animation = {
        "windows, 1, 5, glassy",
        "windowsOut, 1, 5, glassy, popin 80%",
        "border, 1, 8, default",
        "fade, 1, 5, default",
        "workspaces, 1, 6, glassy, slide"
    }
}

local mainMod = "SUPER"

bind = {
    mainMod .. ", Return, exec, alacritty",
    mainMod .. ", B, exec, firefox",
    mainMod .. ", Q, killactive,",
    mainMod .. " SHIFT, E, exit,",
    mainMod .. ", Space, exec, rofi -show drun",
    mainMod .. ", F, fullscreen,",
    mainMod .. ", V, togglefloating,",
    mainMod .. ", P, pseudo,",
    mainMod .. ", W, exec, ~/.config/hypr/scripts/set-wallpaper.sh",
    mainMod .. ", S, exec, ~/.config/hypr/scripts/launch-installer.sh",
    mainMod .. ", 1, workspace, 1",
    mainMod .. ", 2, workspace, 2",
    mainMod .. ", 3, workspace, 3",
    mainMod .. ", 4, workspace, 4",
    mainMod .. ", 5, workspace, 5",
    mainMod .. " SHIFT, 1, movetoworkspace, 1",
    mainMod .. " SHIFT, 2, movetoworkspace, 2",
    mainMod .. " SHIFT, 3, movetoworkspace, 3",
    mainMod .. " SHIFT, 4, movetoworkspace, 4",
    mainMod .. " SHIFT, 5, movetoworkspace, 5"
}