# Fix Home and End keys in native TTY and Emulators
bindkey '^[[1~' beginning-of-line      # Standard Home
bindkey '^[[4~' end-of-line            # Standard End
bindkey '^[[H'  beginning-of-line      # Alternative Home
bindkey '^[[F'  end-of-line            # Alternative End
# Fix Page Up and Page Down keys in native TTY
bindkey '^[[5~' up-line-or-history     # Page Up (Search history backward)
bindkey '^[[6~' down-line-or-history   # Page Down (Search history forward)
# Prompt format when on TTY
# Format: [ username@hostname ] / > sudo foo
PROMPT="%B%F{cyan}[ %n@%m ]%f %F{lightgreen}%~%f %F{white}>%f%b "

CYAN='\033[36m'; GREEN='\033[92m'; BOLD='\033[1m'; RESET='\033[0m'
printf "Welcome to ${CYAN}${BOLD}Liska Linux${RESET} live iso!\n"
printf "Installation guide page:\n"
printf "${GREEN}${BOLD}https://liskalinuxwiki.web.app/installation-guide/${RESET}\n\n"
printf "To connect to a Wi-Fi network, use ${CYAN}nmtui${RESET} utility.\n"
printf "For mobile broadband (WWAN) modems, use ${CYAN}mmcli${RESET} utility.\n"
printf "Ethernet, WLAN and WWAN interfaces using DHCP should work automatically.\n\n"
printf "──────────────────────────────────────────────────────────────────────────────\n\n"
